version: "2"
services:
  api:
    build: .
    environment:
      APP_PORT: 8082
  tester:
    build:
      context: .
      dockerfile: Dockerfile.tester
    environment:
      TEST_REMOTE_ENDPOINT: "api:8082"
      APP_PORT: 3000
    working_dir: /go/src/github.com/sul-dlss-labs/permissions-service
    command: go test test/integration_test.go
    depends_on:
      - api
